config/routes.rb
Rails.application.routes.draw do
  resources :voitures
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "voitures#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/voiture.rb
class Voiture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  before_action :set_voiture, only: %i[ show edit update destroy ]

  # GET /voitures or /voitures.json
  def index
    @voitures = Voiture.all
  end

  # GET /voitures/1 or /voitures/1.json
  def show
  end

  # GET /voitures/new
  def new
    @voiture = Voiture.new
  end

  # GET /voitures/1/edit
  def edit
  end

  # POST /voitures or /voitures.json
  def create
    @voiture = Voiture.new(voiture_params)

    respond_to do |format|
      if @voiture.save
        format.html { redirect_to voiture_url(@voiture), notice: "Voiture was successfully created." }
        format.json { render :show, status: :created, location: @voiture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voitures/1 or /voitures/1.json
  def update
    respond_to do |format|
      if @voiture.update(voiture_params)
        format.html { redirect_to voiture_url(@voiture), notice: "Voiture was successfully updated." }
        format.json { render :show, status: :ok, location: @voiture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voitures/1 or /voitures/1.json
  def destroy
    @voiture.destroy

    respond_to do |format|
      format.html { redirect_to voitures_url, notice: "Voiture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voiture
      @voiture = Voiture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def voiture_params
      params.require(:voiture).permit(:nom, :image, :description, :modele, :lieu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/joueurs_helper.rb
module JoueursHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/voitures_helper.rb
module VoituresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTest3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
  <nav>
  <ul>
  <li>   test nav bar </li>
  
  </ul>
  
  </nav>
    <main class="container mx-auto mt-28 px-5 flex bg-red-700">
      <%= yield %>
    </main>
  </body>
</html>

app/views/voitures/_form.html.erb
<%= form_with(model: voiture, class: "contents") do |form| %>
  <% if voiture.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(voiture.errors.count, "error") %> prohibited this voiture from being saved:</h2>

      <ul>
        <% voiture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nom %>
    <%= form.text_field :nom, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.text_area :image, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :modele %>
    <%= form.text_field :modele, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :lieu %>
    <%= form.text_field :lieu, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/voitures/_voiture.html.erb
<div id="<%= dom_id voiture %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nom:</strong>
    <%= voiture.nom %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Image:</strong>
    <img src="<%= voiture.image %>">
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= voiture.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Modele:</strong>
    <%= voiture.modele %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Lieu:</strong>
    <%= voiture.lieu %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this voiture", voiture, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this voiture', edit_voiture_path(voiture), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/voitures/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-red-500">Editing voiture</h1>

  <%= render "form", voiture: @voiture %>

  <%= link_to "Show this voiture", @voiture, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to voitures", voitures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/voitures/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Voitures</h1>
    <%= link_to 'New voiture', new_voiture_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="voitures" class="min-w-full">
    <%= render @voitures %>
  </div>
</div>

app/views/voitures/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New voiture</h1>

  <%= render "form", voiture: @voiture %>

  <%= link_to 'Back to voitures', voitures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/voitures/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @voiture %>

    <%= link_to 'Edit this voiture', edit_voiture_path(@voiture), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this voiture', voiture_path(@voiture), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to voitures', voitures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>